In [2]:
import pandas as pd
import numpy as np

https://www.census.gov/data/datasets/time-series/demo/popest/2010s-state-total.html

In [3]:
dfPop = pd.read_excel('C:\\Users\\somfl\\Downloads\\nst-est2019-01.xlsx')

In [4]:
dfPop.head(15)

,table with row headers in column A and column headers in rows 3 through 4. (leading dots indicate sub-parts),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,Table 1. Annual Estimates of the Resident Popu...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Geographic Area,2010-04-01 00:00:00,NaN,Population Estimate (as of July 1),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Census,Estimates Base,2010,2011.0,2012.0,2013.0,2014.0,2015.0,2016.0,2017.0,2018.0,2019.0
3,United States,308745538,308758105,309321666,311556874.0,313830990.0,315993715.0,318301008.0,320635163.0,322941311.0,324985539.0,326687501.0,328239523.0
4,Northeast,55317240,55318443,55380134,55604223.0,55775216.0,55901806.0,56006011.0,56034684.0,56042330.0,56059240.0,56046620.0,55982803.0
5,Midwest,66927001,66929725,66974416,67157800.0,67336743.0,67560379.0,67745167.0,67860583.0,67987540.0,68126781.0,68236628.0,68329004.0
6,South,114555744,114563030,114866680,116006522.0,117241208.0,118364400.0,119624037.0,120997341.0,122351760.0,123542189.0,124569433.0,125580448.0
7,West,71945553,71946907,72100436,72788329.0,73477823.0,74167130.0,74925793.0,75742555.0,76559681.0,77257329.0,77834820.0,78347268.0
8,.Alabama,4779736,4780125,4785437,4799069.0,4815588.0,4830081.0,4841799.0,4852347.0,4863525.0,4874486.0,4887681.0,4903185.0
9,.Alaska,710231,710249,713910,722128.0,730443.0,737068.0,736283.0,737498.0,741456.0,739700.0,735139.0,731545.0
10,.Arizona,6392017,6392288,6407172,6472643.0,6554978.0,6632764.0,6730413.0,6829676.0,6941072.0,7044008.0,7158024.0,7278717.0
11,.Arkansas,2915918,2916031,2921964,2940667.0,2952164.0,2959400.0,2967392.0,2978048.0,2989918.0,3001345.0,3009733.0,3017804.0
12,.California,37253956,37254519,37319502,37638369.0,37948800.0,38260787.0,38596972.0,38918045.0,39167117.0,39358497.0,39461588.0,39512223.0
13,.Colorado,5029196,5029319,5047349,5121108.0,5192647.0,5269035.0,5350101.0,5450623.0,5539215.0,5611885.0,5691287.0,5758736.0
14,.Connecticut,3574097,3574147,3579114,3588283.0,3594547.0,3594841.0,3594524.0,3587122.0,3578141.0,3573297.0,3571520.0,3565287.0

In [5]:
dfPop.columns =['state', 'Census', 'Estimates Base', '2010','2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019']

In [6]:
dfPop.drop(columns=['Census', 'Estimates Base'], inplace=True)

In [7]:
dfPop.head(10)

,state,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,Table 1. Annual Estimates of the Resident Popu...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Geographic Area,Population Estimate (as of July 1),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,2010,2011.0,2012.0,2013.0,2014.0,2015.0,2016.0,2017.0,2018.0,2019.0
3,United States,309321666,311556874.0,313830990.0,315993715.0,318301008.0,320635163.0,322941311.0,324985539.0,326687501.0,328239523.0
4,Northeast,55380134,55604223.0,55775216.0,55901806.0,56006011.0,56034684.0,56042330.0,56059240.0,56046620.0,55982803.0
5,Midwest,66974416,67157800.0,67336743.0,67560379.0,67745167.0,67860583.0,67987540.0,68126781.0,68236628.0,68329004.0
6,South,114866680,116006522.0,117241208.0,118364400.0,119624037.0,120997341.0,122351760.0,123542189.0,124569433.0,125580448.0
7,West,72100436,72788329.0,73477823.0,74167130.0,74925793.0,75742555.0,76559681.0,77257329.0,77834820.0,78347268.0
8,.Alabama,4785437,4799069.0,4815588.0,4830081.0,4841799.0,4852347.0,4863525.0,4874486.0,4887681.0,4903185.0
9,.Alaska,713910,722128.0,730443.0,737068.0,736283.0,737498.0,741456.0,739700.0,735139.0,731545.0

In [8]:
dfPop.index

RangeIndex(start=0, stop=66, step=1)

In [9]:
dfPop = dfPop[8:59]

In [10]:
dfPop

,state,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
8,.Alabama,4785437,4799069.0,4815588.0,4830081.0,4841799.0,4852347.0,4863525.0,4874486.0,4887681.0,4903185.0
9,.Alaska,713910,722128.0,730443.0,737068.0,736283.0,737498.0,741456.0,739700.0,735139.0,731545.0
10,.Arizona,6407172,6472643.0,6554978.0,6632764.0,6730413.0,6829676.0,6941072.0,7044008.0,7158024.0,7278717.0
11,.Arkansas,2921964,2940667.0,2952164.0,2959400.0,2967392.0,2978048.0,2989918.0,3001345.0,3009733.0,3017804.0
12,.California,37319502,37638369.0,37948800.0,38260787.0,38596972.0,38918045.0,39167117.0,39358497.0,39461588.0,39512223.0
13,.Colorado,5047349,5121108.0,5192647.0,5269035.0,5350101.0,5450623.0,5539215.0,5611885.0,5691287.0,5758736.0
14,.Connecticut,3579114,3588283.0,3594547.0,3594841.0,3594524.0,3587122.0,3578141.0,3573297.0,3571520.0,3565287.0
15,.Delaware,899593,907381.0,915179.0,923576.0,932487.0,941252.0,948921.0,956823.0,965479.0,973764.0
16,.District of Columbia,605226,619800.0,634924.0,650581.0,662328.0,675400.0,685815.0,694906.0,701547.0,705749.0
17,.Florida,18845537,19053237.0,19297822.0,19545621.0,19845911.0,20209042.0,20613477.0,20963613.0,21244317.0,21477737.0
18,.Georgia,9711881,9802431.0,9901430.0,9972479.0,10067278.0,10178447.0,10301890.0,10410330.0,10511131.0,10617423.0
19,.Hawaii,1363963,1379329.0,1394804.0,1408243.0,1414538.0,1422052.0,1427559.0,1424393.0,1420593.0,1415872.0
20,.Idaho,1570746,1583910.0,1595324.0,1611206.0,1631112.0,1651059.0,1682380.0,1717715.0,1750536.0,1787065.0
21,.Illinois,12840503,12867454.0,12882510.0,12895129.0,12884493.0,12858913.0,12820527.0,12778828.0,12723071.0,12671821.0
22,.Indiana,6490432,6516528.0,6537703.0,6568713.0,6593644.0,6608422.0,6634304.0,6658078.0,6695497.0,6732219.0
23,.Iowa,3050745,3066336.0,3076190.0,3092997.0,3109350.0,3120960.0,3131371.0,3141550.0,3148618.0,3155070.0
24,.Kansas,2858190,2869225.0,2885257.0,2893212.0,2900475.0,2909011.0,2910844.0,2908718.0,2911359.0,2913314.0
25,.Kentucky,4348181,4369821.0,4386346.0,4404659.0,4414349.0,4425976.0,4438182.0,4452268.0,4461153.0,4467673.0
26,.Louisiana,4544532,4575625.0,4600972.0,4624527.0,4644013.0,4664628.0,4678135.0,4670560.0,4659690.0,4648794.0
27,.Maine,1327629,1328284.0,1327729.0,1328009.0,1330513.0,1328262.0,1331317.0,1334612.0,1339057.0,1344212.0
28,.Maryland,5788645,5839419.0,5886992.0,5923188.0,5957283.0,5985562.0,6003323.0,6023868.0,6035802.0,6045680.0
29,.Massachusetts,6566307,6613583.0,6663005.0,6713315.0,6762596.0,6794228.0,6823608.0,6859789.0,6882635.0,6892503.0
30,.Michigan,9877510,9882412.0,9897145.0,9913065.0,9929848.0,9931715.0,9950571.0,9973114.0,9984072.0,9986857.0
31,.Minnesota,5310828,5346143.0,5376643.0,5413479.0,5451079.0,5482032.0,5522744.0,5566230.0,5606249.0,5639632.0
32,.Mississippi,2970548,2978731.0,2983816.0,2988711.0,2990468.0,2988471.0,2987938.0,2988510.0,2981020.0,2976149.0
33,.Missouri,5995974,6010275.0,6024367.0,6040715.0,6056202.0,6071732.0,6087135.0,6106670.0,6121623.0,6137428.0
34,.Montana,990697,997316.0,1003783.0,1013569.0,1021869.0,1030475.0,1040859.0,1052482.0,1060665.0,1068778.0
35,.Nebraska,1829542,1840672.0,1853303.0,1865279.0,1879321.0,1891277.0,1905616.0,1915947.0,1925614.0,1934408.0
36,.Nevada,2702405,2712730.0,2743996.0,2775970.0,2817628.0,2866939.0,2917563.0,2969905.0,3027341.0,3080156.0
37,.New Hampshire,1316762,1320202.0,1324232.0,1326622.0,1333341.0,1336350.0,1342307.0,1348787.0,1353465.0,1359711.0
38,.New Jersey,8799446,8828117.0,8844942.0,8856972.0,8864525.0,8867949.0,8870827.0,8885525.0,8886025.0,8882190.0
39,.New Mexico,2064552,2080450.0,2087309.0,2092273.0,2089568.0,2089291.0,2091630.0,2091784.0,2092741.0,2096829.0
40,.New York,19399878,19499241.0,19572932.0,19624447.0,19651049.0,19654666.0,19633428.0,19589572.0,19530351.0,19453561.0
41,.North Carolina,9574323,9657592.0,9749476.0,9843336.0,9932887.0,10031646.0,10154788.0,10268233.0,10381615.0,10488084.0
42,.North Dakota,674715,685225.0,701176.0,722036.0,737401.0,754066.0,754434.0,754942.0,758080.0,762062.0
43,.Ohio,11539336,11544663.0,11548923.0,11576684.0,11602700.0,11617527.0,11634370.0,11659650.0,11676341.0,11689100.0
44,.Oklahoma,3759944,3788379.0,3818814.0,3853214.0,3878187.0,3909500.0,3926331.0,3931316.0,3940235.0,3956971.0
45,.Oregon,3837491,3872036.0,3899001.0,3922468.0,3963244.0,4015792.0,4089976.0,4143625.0,4181886.0,4217737.0
46,.Pennsylvania,12711160,12745815.0,12767118.0,12776309.0,12788313.0,12784826.0,12782275.0,12787641.0,12800922.0,12801989.0
47,.Rhode Island,1053959,1053649.0,1054621.0,1055081.0,1055936.0,1056065.0,1056770.0,1055673.0,1058287.0,1059361.0
48,.South Carolina,4635649,4671994.0,4717354.0,4764080.0,4823617.0,4891938.0,4957968.0,5021268.0,5084156.0,5148714.0
49,.South Dakota,816166,823579.0,833566.0,842316.0,849129.0,853988.0,862996.0,872868.0,878698.0,884659.0
50,.Tennessee,6355311,6399291.0,6453898.0,6494340.0,6541223.0,6591170.0,6646010.0,6708799.0,6771631.0,6829174.0
51,.Texas,25241971,25645629.0,26084481.0,26480266.0,26964333.0,27470056.0,27914410.0,28295273.0,28628666.0,28995881.0
52,.Utah,2775332,2814384.0,2853375.0,2897640.0,2936879.0,2981835.0,3041868.0,3101042.0,3153550.0,3205958.0
53,.Vermont,625879,627049.0,626090.0,626210.0,625214.0,625216.0,623657.0,624344.0,624358.0,623989.0
54,.Virginia,8023699,8101155.0,8185080.0,8252427.0,8310993.0,8361808.0,8410106.0,8463587.0,8501286.0,8535519.0
55,.Washington,6742830,6826627.0,6897058.0,6963985.0,7054655.0,7163657.0,7294771.0,7423362.0,7523869.0,7614893.0
56,.West Virginia,1854239,1856301.0,1856872.0,1853914.0,1849489.0,1842050.0,1831023.0,1817004.0,1804291.0,1792147.0
57,.Wisconsin,5690475,5705288.0,5719960.0,5736754.0,5751525.0,5760940.0,5772628.0,5790186.0,5807406.0,5822434.0
58,.Wyoming,564487,567299.0,576305.0,582122.0,582531.0,585613.0,584215.0,578931.0,577601.0,578759.0

In [11]:
dfPop['state'] =dfPop['state'].str[1:]

In [12]:
dfPop

,state,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
8,Alabama,4785437,4799069.0,4815588.0,4830081.0,4841799.0,4852347.0,4863525.0,4874486.0,4887681.0,4903185.0
9,Alaska,713910,722128.0,730443.0,737068.0,736283.0,737498.0,741456.0,739700.0,735139.0,731545.0
10,Arizona,6407172,6472643.0,6554978.0,6632764.0,6730413.0,6829676.0,6941072.0,7044008.0,7158024.0,7278717.0
11,Arkansas,2921964,2940667.0,2952164.0,2959400.0,2967392.0,2978048.0,2989918.0,3001345.0,3009733.0,3017804.0
12,California,37319502,37638369.0,37948800.0,38260787.0,38596972.0,38918045.0,39167117.0,39358497.0,39461588.0,39512223.0
13,Colorado,5047349,5121108.0,5192647.0,5269035.0,5350101.0,5450623.0,5539215.0,5611885.0,5691287.0,5758736.0
14,Connecticut,3579114,3588283.0,3594547.0,3594841.0,3594524.0,3587122.0,3578141.0,3573297.0,3571520.0,3565287.0
15,Delaware,899593,907381.0,915179.0,923576.0,932487.0,941252.0,948921.0,956823.0,965479.0,973764.0
16,District of Columbia,605226,619800.0,634924.0,650581.0,662328.0,675400.0,685815.0,694906.0,701547.0,705749.0
17,Florida,18845537,19053237.0,19297822.0,19545621.0,19845911.0,20209042.0,20613477.0,20963613.0,21244317.0,21477737.0
18,Georgia,9711881,9802431.0,9901430.0,9972479.0,10067278.0,10178447.0,10301890.0,10410330.0,10511131.0,10617423.0
19,Hawaii,1363963,1379329.0,1394804.0,1408243.0,1414538.0,1422052.0,1427559.0,1424393.0,1420593.0,1415872.0
20,Idaho,1570746,1583910.0,1595324.0,1611206.0,1631112.0,1651059.0,1682380.0,1717715.0,1750536.0,1787065.0
21,Illinois,12840503,12867454.0,12882510.0,12895129.0,12884493.0,12858913.0,12820527.0,12778828.0,12723071.0,12671821.0
22,Indiana,6490432,6516528.0,6537703.0,6568713.0,6593644.0,6608422.0,6634304.0,6658078.0,6695497.0,6732219.0
23,Iowa,3050745,3066336.0,3076190.0,3092997.0,3109350.0,3120960.0,3131371.0,3141550.0,3148618.0,3155070.0
24,Kansas,2858190,2869225.0,2885257.0,2893212.0,2900475.0,2909011.0,2910844.0,2908718.0,2911359.0,2913314.0
25,Kentucky,4348181,4369821.0,4386346.0,4404659.0,4414349.0,4425976.0,4438182.0,4452268.0,4461153.0,4467673.0
26,Louisiana,4544532,4575625.0,4600972.0,4624527.0,4644013.0,4664628.0,4678135.0,4670560.0,4659690.0,4648794.0
27,Maine,1327629,1328284.0,1327729.0,1328009.0,1330513.0,1328262.0,1331317.0,1334612.0,1339057.0,1344212.0
28,Maryland,5788645,5839419.0,5886992.0,5923188.0,5957283.0,5985562.0,6003323.0,6023868.0,6035802.0,6045680.0
29,Massachusetts,6566307,6613583.0,6663005.0,6713315.0,6762596.0,6794228.0,6823608.0,6859789.0,6882635.0,6892503.0
30,Michigan,9877510,9882412.0,9897145.0,9913065.0,9929848.0,9931715.0,9950571.0,9973114.0,9984072.0,9986857.0
31,Minnesota,5310828,5346143.0,5376643.0,5413479.0,5451079.0,5482032.0,5522744.0,5566230.0,5606249.0,5639632.0
32,Mississippi,2970548,2978731.0,2983816.0,2988711.0,2990468.0,2988471.0,2987938.0,2988510.0,2981020.0,2976149.0
33,Missouri,5995974,6010275.0,6024367.0,6040715.0,6056202.0,6071732.0,6087135.0,6106670.0,6121623.0,6137428.0
34,Montana,990697,997316.0,1003783.0,1013569.0,1021869.0,1030475.0,1040859.0,1052482.0,1060665.0,1068778.0
35,Nebraska,1829542,1840672.0,1853303.0,1865279.0,1879321.0,1891277.0,1905616.0,1915947.0,1925614.0,1934408.0
36,Nevada,2702405,2712730.0,2743996.0,2775970.0,2817628.0,2866939.0,2917563.0,2969905.0,3027341.0,3080156.0
37,New Hampshire,1316762,1320202.0,1324232.0,1326622.0,1333341.0,1336350.0,1342307.0,1348787.0,1353465.0,1359711.0
38,New Jersey,8799446,8828117.0,8844942.0,8856972.0,8864525.0,8867949.0,8870827.0,8885525.0,8886025.0,8882190.0
39,New Mexico,2064552,2080450.0,2087309.0,2092273.0,2089568.0,2089291.0,2091630.0,2091784.0,2092741.0,2096829.0
40,New York,19399878,19499241.0,19572932.0,19624447.0,19651049.0,19654666.0,19633428.0,19589572.0,19530351.0,19453561.0
41,North Carolina,9574323,9657592.0,9749476.0,9843336.0,9932887.0,10031646.0,10154788.0,10268233.0,10381615.0,10488084.0
42,North Dakota,674715,685225.0,701176.0,722036.0,737401.0,754066.0,754434.0,754942.0,758080.0,762062.0
43,Ohio,11539336,11544663.0,11548923.0,11576684.0,11602700.0,11617527.0,11634370.0,11659650.0,11676341.0,11689100.0
44,Oklahoma,3759944,3788379.0,3818814.0,3853214.0,3878187.0,3909500.0,3926331.0,3931316.0,3940235.0,3956971.0
45,Oregon,3837491,3872036.0,3899001.0,3922468.0,3963244.0,4015792.0,4089976.0,4143625.0,4181886.0,4217737.0
46,Pennsylvania,12711160,12745815.0,12767118.0,12776309.0,12788313.0,12784826.0,12782275.0,12787641.0,12800922.0,12801989.0
47,Rhode Island,1053959,1053649.0,1054621.0,1055081.0,1055936.0,1056065.0,1056770.0,1055673.0,1058287.0,1059361.0
48,South Carolina,4635649,4671994.0,4717354.0,4764080.0,4823617.0,4891938.0,4957968.0,5021268.0,5084156.0,5148714.0
49,South Dakota,816166,823579.0,833566.0,842316.0,849129.0,853988.0,862996.0,872868.0,878698.0,884659.0
50,Tennessee,6355311,6399291.0,6453898.0,6494340.0,6541223.0,6591170.0,6646010.0,6708799.0,6771631.0,6829174.0
51,Texas,25241971,25645629.0,26084481.0,26480266.0,26964333.0,27470056.0,27914410.0,28295273.0,28628666.0,28995881.0
52,Utah,2775332,2814384.0,2853375.0,2897640.0,2936879.0,2981835.0,3041868.0,3101042.0,3153550.0,3205958.0
53,Vermont,625879,627049.0,626090.0,626210.0,625214.0,625216.0,623657.0,624344.0,624358.0,623989.0
54,Virginia,8023699,8101155.0,8185080.0,8252427.0,8310993.0,8361808.0,8410106.0,8463587.0,8501286.0,8535519.0
55,Washington,6742830,6826627.0,6897058.0,6963985.0,7054655.0,7163657.0,7294771.0,7423362.0,7523869.0,7614893.0
56,West Virginia,1854239,1856301.0,1856872.0,1853914.0,1849489.0,1842050.0,1831023.0,1817004.0,1804291.0,1792147.0
57,Wisconsin,5690475,5705288.0,5719960.0,5736754.0,5751525.0,5760940.0,5772628.0,5790186.0,5807406.0,5822434.0
58,Wyoming,564487,567299.0,576305.0,582122.0,582531.0,585613.0,584215.0,578931.0,577601.0,578759.0

In [13]:
state_ab = pd.read_excel('C:\\Users\\somfl\\Downloads\\state_ab.xlsx')

In [14]:
state_ab = state_ab.drop(['Unnamed: 2'], axis=1)

In [15]:
state_ab.head()

        State abb
0     Alabama  AL
1      Alaska  AK
2     Arizona  AZ
3    Arkansas  AR
4  California  CA

In [16]:
state_ab.columns = ['state', 'abb']

In [17]:
state_ab.dtypes

state    object
abb      object
dtype: object

In [18]:
dfPop.dtypes

state     object
2010      object
2011     float64
2012     float64
2013     float64
2014     float64
2015     float64
2016     float64
2017     float64
2018     float64
2019     float64
dtype: object

In [19]:
df = dfPop.join(state_ab.set_index('state'), on='state')

In [20]:
df

,state,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,abb
8,Alabama,4785437,4799069.0,4815588.0,4830081.0,4841799.0,4852347.0,4863525.0,4874486.0,4887681.0,4903185.0,AL
9,Alaska,713910,722128.0,730443.0,737068.0,736283.0,737498.0,741456.0,739700.0,735139.0,731545.0,AK
10,Arizona,6407172,6472643.0,6554978.0,6632764.0,6730413.0,6829676.0,6941072.0,7044008.0,7158024.0,7278717.0,AZ
11,Arkansas,2921964,2940667.0,2952164.0,2959400.0,2967392.0,2978048.0,2989918.0,3001345.0,3009733.0,3017804.0,AR
12,California,37319502,37638369.0,37948800.0,38260787.0,38596972.0,38918045.0,39167117.0,39358497.0,39461588.0,39512223.0,CA
13,Colorado,5047349,5121108.0,5192647.0,5269035.0,5350101.0,5450623.0,5539215.0,5611885.0,5691287.0,5758736.0,CO
14,Connecticut,3579114,3588283.0,3594547.0,3594841.0,3594524.0,3587122.0,3578141.0,3573297.0,3571520.0,3565287.0,CT
15,Delaware,899593,907381.0,915179.0,923576.0,932487.0,941252.0,948921.0,956823.0,965479.0,973764.0,DE
16,District of Columbia,605226,619800.0,634924.0,650581.0,662328.0,675400.0,685815.0,694906.0,701547.0,705749.0,NaN
17,Florida,18845537,19053237.0,19297822.0,19545621.0,19845911.0,20209042.0,20613477.0,20963613.0,21244317.0,21477737.0,FL
18,Georgia,9711881,9802431.0,9901430.0,9972479.0,10067278.0,10178447.0,10301890.0,10410330.0,10511131.0,10617423.0,GA
19,Hawaii,1363963,1379329.0,1394804.0,1408243.0,1414538.0,1422052.0,1427559.0,1424393.0,1420593.0,1415872.0,HI
20,Idaho,1570746,1583910.0,1595324.0,1611206.0,1631112.0,1651059.0,1682380.0,1717715.0,1750536.0,1787065.0,ID
21,Illinois,12840503,12867454.0,12882510.0,12895129.0,12884493.0,12858913.0,12820527.0,12778828.0,12723071.0,12671821.0,IL
22,Indiana,6490432,6516528.0,6537703.0,6568713.0,6593644.0,6608422.0,6634304.0,6658078.0,6695497.0,6732219.0,IN
23,Iowa,3050745,3066336.0,3076190.0,3092997.0,3109350.0,3120960.0,3131371.0,3141550.0,3148618.0,3155070.0,IA
24,Kansas,2858190,2869225.0,2885257.0,2893212.0,2900475.0,2909011.0,2910844.0,2908718.0,2911359.0,2913314.0,KS
25,Kentucky,4348181,4369821.0,4386346.0,4404659.0,4414349.0,4425976.0,4438182.0,4452268.0,4461153.0,4467673.0,KY
26,Louisiana,4544532,4575625.0,4600972.0,4624527.0,4644013.0,4664628.0,4678135.0,4670560.0,4659690.0,4648794.0,LA
27,Maine,1327629,1328284.0,1327729.0,1328009.0,1330513.0,1328262.0,1331317.0,1334612.0,1339057.0,1344212.0,ME
28,Maryland,5788645,5839419.0,5886992.0,5923188.0,5957283.0,5985562.0,6003323.0,6023868.0,6035802.0,6045680.0,MD
29,Massachusetts,6566307,6613583.0,6663005.0,6713315.0,6762596.0,6794228.0,6823608.0,6859789.0,6882635.0,6892503.0,MA
30,Michigan,9877510,9882412.0,9897145.0,9913065.0,9929848.0,9931715.0,9950571.0,9973114.0,9984072.0,9986857.0,MI
31,Minnesota,5310828,5346143.0,5376643.0,5413479.0,5451079.0,5482032.0,5522744.0,5566230.0,5606249.0,5639632.0,MN
32,Mississippi,2970548,2978731.0,2983816.0,2988711.0,2990468.0,2988471.0,2987938.0,2988510.0,2981020.0,2976149.0,MS
33,Missouri,5995974,6010275.0,6024367.0,6040715.0,6056202.0,6071732.0,6087135.0,6106670.0,6121623.0,6137428.0,MO
34,Montana,990697,997316.0,1003783.0,1013569.0,1021869.0,1030475.0,1040859.0,1052482.0,1060665.0,1068778.0,MT
35,Nebraska,1829542,1840672.0,1853303.0,1865279.0,1879321.0,1891277.0,1905616.0,1915947.0,1925614.0,1934408.0,NE
36,Nevada,2702405,2712730.0,2743996.0,2775970.0,2817628.0,2866939.0,2917563.0,2969905.0,3027341.0,3080156.0,NV
37,New Hampshire,1316762,1320202.0,1324232.0,1326622.0,1333341.0,1336350.0,1342307.0,1348787.0,1353465.0,1359711.0,NH
38,New Jersey,8799446,8828117.0,8844942.0,8856972.0,8864525.0,8867949.0,8870827.0,8885525.0,8886025.0,8882190.0,NJ
39,New Mexico,2064552,2080450.0,2087309.0,2092273.0,2089568.0,2089291.0,2091630.0,2091784.0,2092741.0,2096829.0,NM
40,New York,19399878,19499241.0,19572932.0,19624447.0,19651049.0,19654666.0,19633428.0,19589572.0,19530351.0,19453561.0,NY
41,North Carolina,9574323,9657592.0,9749476.0,9843336.0,9932887.0,10031646.0,10154788.0,10268233.0,10381615.0,10488084.0,NC
42,North Dakota,674715,685225.0,701176.0,722036.0,737401.0,754066.0,754434.0,754942.0,758080.0,762062.0,ND
43,Ohio,11539336,11544663.0,11548923.0,11576684.0,11602700.0,11617527.0,11634370.0,11659650.0,11676341.0,11689100.0,OH
44,Oklahoma,3759944,3788379.0,3818814.0,3853214.0,3878187.0,3909500.0,3926331.0,3931316.0,3940235.0,3956971.0,OK
45,Oregon,3837491,3872036.0,3899001.0,3922468.0,3963244.0,4015792.0,4089976.0,4143625.0,4181886.0,4217737.0,OR
46,Pennsylvania,12711160,12745815.0,12767118.0,12776309.0,12788313.0,12784826.0,12782275.0,12787641.0,12800922.0,12801989.0,PA
47,Rhode Island,1053959,1053649.0,1054621.0,1055081.0,1055936.0,1056065.0,1056770.0,1055673.0,1058287.0,1059361.0,RI
48,South Carolina,4635649,4671994.0,4717354.0,4764080.0,4823617.0,4891938.0,4957968.0,5021268.0,5084156.0,5148714.0,SC
49,South Dakota,816166,823579.0,833566.0,842316.0,849129.0,853988.0,862996.0,872868.0,878698.0,884659.0,SD
50,Tennessee,6355311,6399291.0,6453898.0,6494340.0,6541223.0,6591170.0,6646010.0,6708799.0,6771631.0,6829174.0,TN
51,Texas,25241971,25645629.0,26084481.0,26480266.0,26964333.0,27470056.0,27914410.0,28295273.0,28628666.0,28995881.0,TX
52,Utah,2775332,2814384.0,2853375.0,2897640.0,2936879.0,2981835.0,3041868.0,3101042.0,3153550.0,3205958.0,UT
53,Vermont,625879,627049.0,626090.0,626210.0,625214.0,625216.0,623657.0,624344.0,624358.0,623989.0,VT
54,Virginia,8023699,8101155.0,8185080.0,8252427.0,8310993.0,8361808.0,8410106.0,8463587.0,8501286.0,8535519.0,VA
55,Washington,6742830,6826627.0,6897058.0,6963985.0,7054655.0,7163657.0,7294771.0,7423362.0,7523869.0,7614893.0,WA
56,West Virginia,1854239,1856301.0,1856872.0,1853914.0,1849489.0,1842050.0,1831023.0,1817004.0,1804291.0,1792147.0,WV
57,Wisconsin,5690475,5705288.0,5719960.0,5736754.0,5751525.0,5760940.0,5772628.0,5790186.0,5807406.0,5822434.0,WI
58,Wyoming,564487,567299.0,576305.0,582122.0,582531.0,585613.0,584215.0,578931.0,577601.0,578759.0,WY

In [21]:
state_ab.shape

(50, 2)

In [22]:
df.loc[df['state']=='District of Columbia', 'abb'] = 'DC'

In [23]:
df['population'] = (df['2010'] + df['2011'] + df['2012'] + df['2013'] + df['2014'] + df['2015'] + df['2016'] +
                    df['2017'] + df['2018'] )//9

In [24]:
df = df.drop(['2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019'], axis=1)

In [25]:
df

                   state abb  population
8                Alabama  AL   4838890.0
9                 Alaska  AK    732625.0
10               Arizona  AZ   6752305.0
11              Arkansas  AR   2968959.0
12            California  CA  38518853.0
13              Colorado  CO   5363694.0
14           Connecticut  CT   3584598.0
15              Delaware  DE    932299.0
16  District of Columbia  DC    658947.0
17               Florida  FL  19957619.0
18               Georgia  GA  10095255.0
19                Hawaii  HI   1406163.0
20                 Idaho  ID   1643776.0
21              Illinois  IL  12839047.0
22               Indiana  IN   6589257.0
23                  Iowa  IA   3104235.0
24                Kansas  KS   2894032.0
25              Kentucky  KY   4411215.0
26             Louisiana  LA   4629186.0
27                 Maine  ME   1330601.0
28              Maryland  MD   5938231.0
29         Massachusetts  MA   6742118.0
30              Michigan  MI   9926605.0
31             Minnesota  MN   5452825.0
32           Mississippi  MS   2984245.0
33              Missouri  MO   6057188.0
34               Montana  MT   1023523.0
35              Nebraska  NE   1878507.0
36                Nevada  NV   2837164.0
37         New Hampshire  NH   1333563.0
38            New Jersey  NJ   8856036.0
39            New Mexico  NM   2086622.0
40              New York  NY  19572840.0
41        North Carolina  NC   9954877.0
42          North Dakota  ND    726897.0
43                  Ohio  OH  11600021.0
44              Oklahoma  OK   3867324.0
45                Oregon  OR   3991724.0
46          Pennsylvania  PA  12771597.0
47          Rhode Island  RI   1055560.0
48        South Carolina  SC   4840891.0
49          South Dakota  SD    848145.0
50             Tennessee  TN   6551297.0
51                 Texas  TX  26969453.0
52                  Utah  UT   2950656.0
53               Vermont  VT    625335.0
54              Virginia  VA   8290015.0
55            Washington  WA   7098979.0
56         West Virginia  WV   1840575.0
57             Wisconsin  WI   5748351.0
58               Wyoming  WY    577678.0

In [27]:
SavePath = "C:\\Users\\somfl\\Documents\\Data Science Career Track\\LendingClub\\population.csv"
df.to_csv(SavePath, sep =" ", index=False)